wandb:
  enabled: true        # whether to use the wandb logger or not
  offline: false       # log in offline mode (saved locally, synced later). Useful with no internet access.
  project_name: sensor-agnostic-underwater-localization  # name of the project
  entity: philippdahlinger   # wandb entity. null -> your default (private) account
  group_name: ${exp_name}
  run_name: ${model.name}_seed_${seed}
  dev: false           # mark this run in wandb as a development run
  #  job_type: ${hydra:job.override_dirname}
  # only used for categorizing wandb projects
  tags: null           # list of custom tags to sort/find these runs by
